#!/bin/sh

# This job requests number_of_tasks MPI tasks (without OpenMP)
# SBATCH -N 1
# SBATCH -n 1
# SBATCH -c 1
#SBATCH -n 1
#SBATCH -c 128
#SBATCH -t 72:00:00
# SBATCH --ntasks-per-socket=2
#SBATCH --cpus-per-task=128
#SBATCH -p shared
#SBATCH -o ./out/output.%j.out # STDOUT
# SBATCH --mem=246G 
export OMP_PROC_BIND=true
export OMP_PLACES=cores
export OMP_NUM_THREADS=128
export OMP_AFFINITY=balanced
# export I_MPI_GTOOL="vtune -c hpc-performance -r HPC:all" 
# mpiexec ./wetP
seed="520224"
module load gcc/11.2
module load openmpi/4.1.1
mkdir out

./run6.exe $seed

#mpirun valgrind --tool=massif ./run2.exe 1
#
# ./wetP
#valgrind ./wetP
#./wetP
