#!/bin/sh

# This job requests number_of_tasks MPI tasks (without OpenMP)
# SBATCH -N 1
# SBATCH -n 1
# SBATCH -c 1
#SBATCH -n 1
#SBATCH -c 64
#SBATCH -t 1:00:00
# SBATCH --ntasks-per-socket=2
#SBATCH --cpus-per-task=64
#SBATCH -p shared
#SBATCH -o ./out/output.%j.out # STDOUT
# SBATCH --mem=8G 
module load gcc/11.2
module load openmpi/4.1.1
export OMP_PROC_BIND=true
export OMP_PLACES=cores
export OMP_NUM_THREADS=64
export OMP_AFFINITY=balanced
# export I_MPI_GTOOL="vtune -c hpc-performance -r HPC:all" 
# mpiexec ./wetP
seed="405415"
./run.exe $seed
#mpirun ./run.exe $seed

#mpirun valgrind --tool=massif ./run2.exe 1
#
# ./wetP
#valgrind ./wetP
#./wetP