#!/bin/sh

# Grid Engine options
#$ -N liquidlens
#$ -cwd
#$ -pe sharedmem 16
#$ -l h_rt=00:05:00
#$ -o ./output.%j.out # STDOUT

module load phys/compilers/gcc/11.2.0
module load phys/compilers/openmpi/4.0.0-gcc82

export OMP_PROC_BIND=true
export OMP_PLACES=cores
export OMP_NUM_THREADS=$NSLOTS
export OMP_AFFINITY=balanced

# Create output directory
mkdir -p out

./run.exe