#!/bin/sh

# This job requests number_of_tasks MPI tasks (without OpenMP)
#SBATCH -n 1
#SBATCH -c 16
#SBATCH -t 00:15:00
#SBATCH --cpus-per-task=16
#SBATCH -p shared
#SBATCH -o ./output.%j.out # STDOUT
mkdir out
module load gcc/11.2
module load openmpi/4.1.1
module load python
export OMP_PROC_BIND=true
export OMP_PLACES=cores
export OMP_NUM_THREADS=16
export OMP_AFFINITY=balanced

./run.exe
python Analysis.py
