#!/bin/sh

# This job requests number_of_tasks MPI tasks (without OpenMP)
#SBATCH -n 10
#SBATCH -c 12
#SBATCH -t 00:15:00
#SBATCH --cpus-per-task=12
#SBATCH -p test
#SBATCH -o ./out/output.%j.out # STDOUT
mkdir out
module load gcc/11.2
module load openmpi/4.1.1
export OMP_PROC_BIND=true
export OMP_PLACES=cores
export OMP_NUM_THREADS=12
export OMP_AFFINITY=balanced

mpirun ./run.exe

