name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: mpi4py/setup-mpi@v1
      - run: make -C tests/unit gtest
      - run: make -C tests/unit
